<?php

namespace Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable; 

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            'DUTY' => new ReferenceField(
                'duty', 
                DoctorDutyPropertyValuesTable::class, 
                ['=this.duty_id' => 'ref.IBLOCK_ELEMENT_ID']
            ),
            'PROCEDURES' => new ReferenceField(
                'procedures', 
                DoctorProceduresPropertyValuesTable::class, 
                ['=this.procedures_id' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
